# Values needed for Historian

# Deprecated: only here for backwards compatibility
historianApi:
  enabled: false

metricsExporter:
  enabled: false

image:
  repository: mongo
  tag: 7.0.15
    
annotations:
  teknoir.org/managed-by: devstudio
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 128Mi
nodePort:
  enabled: false
  nodePort: 31017
