# Values needed for Historian
metricsExporter:
  enabled: false

annotations:
  teknoir.org/managed-by: devstudio
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 128Mi
