---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: historian-api
  name: historian-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: historian-api
