# Deprecated
{{- if .Values.historianApi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: historian-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: historian-api
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
      {{- if .Values.nodePort.enabled }}
      nodePort: 31380
      {{- end }}
  selector:
    app: historian-api
  {{- end }}