---
apiVersion: v1
kind: Service
metadata:
  name: historian-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: historian-db
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-native
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: historian-db
