# Deprecated
{{- if .Values.historianApi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: historian-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: historian-api
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: historian-api
  {{- end }}